### ISSUE TITLE
Error: Unsupported argument

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/terraform-gitops-db2#11]
**bala@Bala Office terraform % terraform plan
╷**
│ Error: Unsupported argument
│ 
│   **on main.tf line 54, in module "gitops-db2":**
│   54:   namespace = module.namespace.name
│ 
│ An argument named "namespace" is not expected here.
╵
**bala@Bala Office terraform % terraform apply**
╷
│ Error: Unsupported argument
│ 
│   **on main.tf line 54, in module "gitops-db2":**
│   54:   namespace = module.namespace.name
│ 
│ An argument named "namespace" is not expected here.
╵
bala@Bala Office terraform %

**Comment by triceam** [comment]
@yogendrasri The latest code for the DB2U module is already merged, and the problem still exists.  It looks like the `namespace` variable assignment is being generated by iascable, but the `namespace` variable does not exist on the db2u module:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/974294/159985021-96f4c725-298c-4e4b-b296-d1728289d945.png">

I think this will go away if you remove the `namespace` dependency from [`module.yaml`](https://github.com/cloud-native-toolkit/terraform-gitops-db2u-operator/blob/main/module.yaml) (assuming you don't need it):

<img width="724" alt="image" src="https://user-images.githubusercontent.com/974294/159985203-1ed5154a-d387-4979-a972-e49a8f8f16f9.png">

**Comment by yogendrasri** [comment]
Thank you @triceam I have fixed it, Please review and approve this pull request

**Comment by yogendrasri** [comment]
@balasgit

**Comment by balasgit** [comment]
Thanks @yogendrasri
